#!/bin/sh
# Usage: to-next <isolatin-file> <next-file>
if test $# != 2; then
  echo "Usage: ${CHARSETBINDIR}to-next <isolatin-file> <next-file>"
  exit 1
fi
${CHARSETBINDIR}cv-to-next < "$1" > "$2"
${CHARSETBINDIR}touchr "$1" "$2"
