"         Copyright (c) 1992, 1993, 1994 Bruno Haible and Michael Stoll" CRLFstring
"                           All Rights Reserved" CRLFstring
"" CRLFstring
"" CRLFstring
"Summary:" CRLFstring
"" CRLFstring
"  Permission is granted to use, copy, modify this program," CRLFstring
"  EXCEPT that the copyright notice must be reproduced on copies, and" CRLFstring
"  credit should be given to the authors where it is due." CRLFstring
"  WE MAKE NO WARRANTY AND ACCEPT NO LIABILITY FOR THIS PROGRAM." CRLFstring
"" CRLFstring
"" CRLFstring
"In detail:" CRLFstring
"" CRLFstring
"  1. Permission to use, copy, modify this software and its documentation" CRLFstring
"     for any purpose is hereby granted without fee, provided that" CRLFstring
"     - the above copyright notice appear in all copies," CRLFstring
"     - both that copyright notice and this permission notice appear in" CRLFstring
"       supporting documentation, and that" CRLFstring
"     - you cause modified files to carry prominent notices stating that" CRLFstring
"       you changed the files and the date of any change." CRLFstring
"" CRLFstring
"  2. Please notify us if you are going to sell this software or its" CRLFstring
"     documentation for profit." CRLFstring
"" CRLFstring
"  3. WE DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL" CRLFstring
"     IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL" CRLFstring
"     WE BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR" CRLFstring
"     ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS," CRLFstring
"     WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION," CRLFstring
"     ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS" CRLFstring
"     SOFTWARE." CRLFstring
"" CRLFstring
"" CRLFstring
"Additionally:" CRLFstring
"" CRLFstring
"  This program is free software; you can redistribute it and/or modify" CRLFstring
"  it under the terms of the GNU General Public License version 2 as" CRLFstring
"  published by the Free Software Foundation; see file GNU-GPL." CRLFstring
"" CRLFstring
"  This program is distributed in the hope that it will be useful," CRLFstring
"  but WITHOUT ANY WARRANTY; without even the implied warranty of" CRLFstring
"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the" CRLFstring
"  GNU General Public License for more details." CRLFstring
"" CRLFstring
"  You should have received a copy of the GNU General Public License" CRLFstring
"  along with this program; if not, write to the Free Software" CRLFstring
"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA." CRLFstring
"" CRLFstring
"" CRLFstring
"Note:" CRLFstring
"" CRLFstring
"  This copyright does *not* cover user programs that run in CLISP, if" CRLFstring
"  they don't reference symbols in CLISP's built-in packages (except" CRLFstring
"  the packages LISP, USER, COMMON-LISP, COMMON-LISP-USER, KEYWORD)," CRLFstring
"  i.e. if they don't rely on CLISP internals and would as well run in any" CRLFstring
"  other Common Lisp implementation. Such user programs are not covered" CRLFstring
"  by the term \"derived work\" used in the GNU GPL. Neither is their" CRLFstring
"  compiled code, i.e. the result of compiling them by use of the function" CRLFstring
"  COMPILE-FILE. We refer to such user programs as \"independent work\"." CRLFstring
"" CRLFstring
"  You may copy and distribute memory image files generated by the" CRLFstring
"  function SAVEINITMEM, if it was generated only from CLISP and independent" CRLFstring
"  work, and provided that you accompany them, in the sense of section 3" CRLFstring
"  of the GNU GPL, with the source code of CLISP - precisely the same CLISP" CRLFstring
"  version that was used to build the memory image -, the source or compiled" CRLFstring
"  code of the user programs needed to rebuild the memory image (source" CRLFstring
"  code for all the parts that are not independent work, see above), and" CRLFstring
"  a precise description how to rebuild the memory image from these." CRLFstring
"" CRLFstring
"" CRLFstring
"Authors:" CRLFstring
"  Generic CLISP: Bruno Haible, Michael Stoll" CRLFstring
"  Atari version: Bruno Haible, Michael Stoll" CRLFstring
"  Amiga version: Bruno Haible, Jörg Höhle" CRLFstring
"  Acorn version: Bruno Haible, Peter Burwood" CRLFstring
"  DOS version:   Bruno Haible, Bernhard Degel, Jürgen Weber" CRLFstring
"  OS/2 version:  Bruno Haible" CRLFstring
"  Unix version:  Bruno Haible" CRLFstring
"  PCL:           Richard Harris, ported by Bruno Haible" CRLFstring
"  Punimax:       Bill Schelter, ported by Bruno Haible" CRLFstring
"" CRLFstring
"Maintenance:     Bruno Haible, Marcus Daniels" CRLFstring
"" CRLFstring
"Email addresses (September 1992 or newer):" CRLFstring
"  Bruno Haible     haible@clisp.cons.org" CRLFstring
"  Michael Stoll    michael@rhein.iam.uni-bonn.de" CRLFstring
"  Jörg Höhle       Joerg.Hoehle@gmd.de" CRLFstring
"  Peter Burwood    clisp@arcangel.dircon.co.uk" CRLFstring
"  Marcus Daniels   marcus@sysc.pdx.edu" CRLFstring
"  Richard Harris   harrisr@cs.rpi.edu" CRLFstring
"  Bill Schelter    wfs@rascal.ics.utexas.edu" CRLFstring
"" CRLFstring
